version: '3.7' # nurodoma naudojama 'docker-compose' versija
services:  # sąrašas kuriuos service norėsim paleist (veikia panašiu principu, kaip ansible yml "task:")
  server:
    image: postgrest/postgrest # image pavadinimas, pagal kurį sukursim konteinerį
    ports:
      - '{{ generated_port }}:3000' # atidarytas (exposed) OpenNebula VM portas : local OpenNebula VM portas
    links: # services kurie priklauso vienas nuo kito
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: 'http://127.0.0.1:3000'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '{{ generated_port }}:5432'
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:  # išsaugo nurodytuose failuose esančius duomenis konteineryje
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # nurodo kokio failo duomenis išsaugoti
      - ./pgdata:/var/lib/postgresql/data #išsaugo duomenis

# NOTES:
  # depends_on - Express dependency between services.
  # links - Link to containers in another service and also express dependency between services in the same way as depends_on.