version: '3.7'
services:  
  server:
    image: postgrest/postgrest
    ports:
      - '{{ generated_port }}:3000'
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: 'http://127.0.0.1:3000'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '{{ generated_port }}:5432'
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql #place where you need to put your init.sql in the docker container