---
- hosts: all
  become: yes
  vars:
    ansible_become_pass: "{{ your_sudo_pass }}"
    ansible_python_interpreter: "/usr/bin/python3" 
  tasks:
# ===================CLIENT========================

  - name: Update debian
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: 1. Install apt-transport-https
    ansible.builtin.apt:
      state: latest
      update_cache: true

  - name: 2. Add Apt signing key
    ansible.builtin.apt_key:
      url: "https://dl.google.com/linux/linux_signing_key.pub"
      state: present

  - name: 3. Add repository into sources list
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: google-chrome

  - name: 4. Install google-chrome-stable
    ansible.builtin.apt:
      name: "google-chrome-stable"
      state: latest
      update_cache: true

# ===================WEBSERVER========================

  - name: Update debian
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: 1. Install Apache
    apt: name=apache2 state=present

  - name: 2. Install MySQL
    apt: name=mariadb-server state=present

  - name: 3. Install php mods
    apt: name=libapache2-mod-php state=present

  - name: 4. Delete static files from www
    file:
      path: /var/www/html/index.html
      state: absent

  - name: 5. Add hello world script
    copy:
      src: ~/web/index.php
      dest: /var/www/html/index.php

  - name: 6. Change directory permissions
    file:
      path: /html
      state: directory
      group: www-data
      recurse: yes
      mode: g+rx

# ===================DATABASE========================

  - name: Update debian
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install Docker Module for Python to run Docker
    pip:
      name: docker

  - name: Ensure docker-compose is installed and available
    get_url:
      url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-{{ ansible_system }>
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Update debian
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

# doesnt work
  - name: Show Output of Hello World Example
    debug:
      msg: "Container Output: {{hello_world_output.stdout}}"

# doesnt work      
  - name: Check Container Status
    command: docker ps
    register: res
  - debug: var=res.stdout

  - name: Copy Needed Files from Ansible Machine Machine to Remote hosts
    copy:
      src:  /root/projects/{{ item }}
      dest: /home/
    with_items:
      - docker-compose.yml
      - init.sql

  - name: Go to Directory Where Files Have Been Placed and Create PostgREST Docker DB Server and DB Cont>
    command: chdir=/home/ docker-compose up -d

  - name: Clean Artifact Path
    ansible.builtin.file:
      path: /root/projects/{{ item }}
      state: absent
      with_items:
        - docker-compose.yml
        - init.sql