---
- hosts: webservers
  become: yes
  vars:
    ansible_become_pass: "{{ your_sudo_pass }}"
    ansible_python_interpreter: "/usr/bin/python3" 
  tasks:
  - name: Update debian
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: 1. Install Apache
    apt: name=apache2 state=present

  - name: 2. Install MySQL
    apt: name=mariadb-server state=present

  - name: 3. Install php mods
    apt: name=libapache2-mod-php state=present

  - name: 4. Delete static files from www
    file:
      path: /var/www/html/index.html
      state: absent

  - name: 5. Add hello world script
    copy:
      src: /root/projects/web/index.php
      dest: /var/www/html/index.php

  - name: 6. Change directory permissions
    file:
      path: /html
      state: directory
      group: www-data
      recurse: yes
      mode: g+rx